version: '2'
services:
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  video_service:
    image: video_service
    links:
      - mysql
    ports: 
      - "8086:8086"
    